# Basic Site Settings
locale                   : "en-US"
title                    : "Yuying Wu/Personal Homepage"
title_separator          : "-"
name                     : &name "Yuying Wu"
description              : &description "personal description"
url                      : https://yuyingwu-aurora.github.io/yuying/
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "yuyingwu-aurora.github.io/yuying"

# Site Author
author:
  # Biographic information
  avatar           : "CV照.png"
  name             : "Yuying Wu"
  pronouns         : # example: "she/her"  
  bio              : "PhD in Economics"
  location         : "UK"
  employer         : "University of Birmingham"
  uri              : https://www.birmingham.ac.uk/
  email            : "YXW1043@STUDENT.BHAM.AC.UK" 
  
  # Social media
  linkedin         : # https://www.linkedin.com/in/yuying-wu-206021335/


# Site Settings
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page
comments:
  provider               : # false (default), "disqus", "discourse", "facebook", "google-plus", "staticman", "custom"
  disqus:
    shortname            :
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages" # "master", "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601" # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds"
atom_feed:
  hide                   : false     # change to true to hide the RSS feed in the footer
  path                   : # blank (default) uses feed.xml


